import { readFile, writeFile, mkdir, chmod, access } from 'node:fs/promises';
import { dirname } from 'node:path';

/**
 * Generates the bash script content from the user's configuration.
 * @param {object} config - { items: [{item, cfg}], separator, scriptPath }
 * @returns {string} bash script content
 */
export function generateScript(config) {
  const { items: selectedItems, separator } = config;
  const date = new Date().toISOString().split('T')[0];

  const itemBlocks = selectedItems.map(({ item, cfg }) => {
    const bashCode = item.generateBash(cfg);
    return `# --- ${item.name} ---\n${bashCode}`;
  });

  const partsPush = selectedItems
    .map(({ item }) => `[ -n "$${item.varName}" ] && parts+=("$${item.varName}")`)
    .join('\n');

  // Escape the separator for bash
  const sepEscaped = separator.replace(/"/g, '\\"');

  return `#!/bin/bash
# Claude Code Statusline — generated by statuscraft
# ${date}

input=$(cat)
cwd=$(echo "$input" | jq -r '.workspace.current_dir // "$HOME"')

parts=()

${itemBlocks.join('\n\n')}

${partsPush}

# Join with separator
result=""
for i in "\${!parts[@]}"; do
  if [ $i -eq 0 ]; then result="\${parts[$i]}"
  else result="\${result} ${sepEscaped} \${parts[$i]}"
  fi
done

printf "%s" "$result"
`;
}

/**
 * Generates an ASCII preview of the statusline with example values.
 * @param {object} config - { items: [{item, cfg}], separator }
 * @returns {string} preview string
 */
export function generatePreview(config) {
  const { items: selectedItems, separator } = config;

  const parts = selectedItems.map(({ item, cfg }) => {
    const label = cfg.label ? `${cfg.label} ` : '';

    // Use mode-specific example if available
    if (item.exampleValues && cfg.mode) {
      return `${label}${item.exampleValues[cfg.mode]}`;
    }

    // Special case: git_branch default prefix
    if (item.id === 'git_branch' && !cfg.label) {
      return `⎇ ${item.exampleValue}`;
    }

    return `${label}${item.exampleValue}`;
  });

  return parts.join(` ${separator} `);
}

/**
 * Writes the bash script to disk and updates settings.json.
 * @param {object} config - full config
 * @returns {{ scriptPath: string, settingsPath: string, settingsExisted: boolean, hadStatusLine: boolean }}
 */
export async function writeFiles(config) {
  const { scriptPath } = config;
  const settingsPath = `${process.env.HOME}/.claude/settings.json`;

  // Ensure directory exists
  await mkdir(dirname(scriptPath), { recursive: true });

  // Write bash script
  const script = generateScript(config);
  await writeFile(scriptPath, script, 'utf-8');
  await chmod(scriptPath, 0o755);

  // Read existing settings
  let settings = {};
  let settingsExisted = false;
  let hadStatusLine = false;

  try {
    await access(settingsPath);
    settingsExisted = true;
    const raw = await readFile(settingsPath, 'utf-8');
    settings = JSON.parse(raw);
    if (settings.statusLine) {
      hadStatusLine = true;
    }
  } catch {
    // No existing settings file or invalid JSON — start fresh
  }

  // Merge only the statusLine key
  settings.statusLine = {
    type: 'command',
    command: scriptPath,
  };

  // Ensure settings directory exists
  await mkdir(dirname(settingsPath), { recursive: true });
  await writeFile(settingsPath, JSON.stringify(settings, null, 2) + '\n', 'utf-8');

  return { scriptPath, settingsPath, settingsExisted, hadStatusLine };
}
